### ISSUE TITLE
CLI error "Graph node 'Magento_Csp' is linked to itself."

### ISSUE THREAD

**Issue by alexwatever** [baldwin-agency/magento2-module-csp-shim#3]
Thank you for the great work on this module.

We installed this on Magento v2.4.5-p8 when we use some Magento CLI commands, such as `bin/magento module:disable`, we get the below warning. It seems to work otherwise, and we can bypass this by using the force (`-f`) feature.

![Screen Shot 2024-06-18 at 14 02 36](https://github.com/baldwin-agency/magento2-module-csp-shim/assets/1897655/ad075155-4a6a-41d5-8db3-46e28797b15c)

**Comment by hostep** [comment]
Thanks, I can confirm the problem, no idea why it happens though, will try to debug a bit later this week.

**Comment by hostep** [comment]
Fixed in version [1.0.3](https://github.com/baldwin-agency/magento2-module-csp-shim/releases/tag/v1.0.3), by 182ca54, thanks for letting me know about this problem.

**Comment by alexwatever** [comment]
Thanks mate, I appreciate the help.
